export type PageName =
  | "dashboard"
  | "single-payment"
  | "bulk-upload"
  | "approvals"
  | "analytics"
  | "transactions"
  | "fund-account"
  | "settings"
  | "help"
  | "reports"
  | "templates"
  | "merchants"
  | "collections"
  | "new-collection"
  | "user-management"
  | "payments"
  | "request-payment";
